import type { Metadata } from 'next';
import Link from 'next/link';
import { BUSINESS, SERVICE_AREAS } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'About Benson Home Solutions',
  description: 'Benson Enterprises, LLC dba Benson Home Solutions provides construction, repair, reconstruction, property maintenance, and rural project services in Harney County, Oregon.',
  alternates: { canonical: `${BUSINESS.url}/about` },
};

export default function AboutPage() {
  return <>
    <section className="bg-[#F5F1E8]"><div className="mx-auto max-w-6xl px-5 py-16 md:py-24"><p className="font-semibold uppercase tracking-[0.16em] text-[#722F37]">{BUSINESS.legalName} · {BUSINESS.license}</p><h1 className="mt-4 max-w-4xl text-4xl font-bold text-[#4A1F24] md:text-6xl">A general contractor built around practical scopes and rural logistics.</h1><p className="mt-6 max-w-3xl text-lg leading-8">Benson Home Solutions provides residential and light-commercial construction, repair, reconstruction, property maintenance, demolition, and site work. Harney County is the primary public service area, including projects where travel, access, weather, materials, disposal, and subcontractor availability are part of the job from the start.</p></div></section>

    <section className="mx-auto grid max-w-6xl gap-12 px-5 py-14 md:grid-cols-2 md:py-20"><div><h2 className="text-3xl font-bold text-[#4A1F24]">How we work</h2><p className="mt-4 text-lg leading-8">A useful construction scope starts with the condition on the property. We review what is damaged, what needs to stay, what another licensed trade must handle, how the site can be accessed, and what the next phase depends on. That is especially important on remote work where a missing fitting, wrong measurement, or unplanned disposal trip can cost a day.</p><p className="mt-5 text-lg leading-8">Documentation matters on repair, insurance-loss, vacant-property, and multi-trade work. Photos, written scopes, change documentation, and clear sequencing make it easier for owners, subcontractors, insurers, and future decision-makers to understand what was done.</p></div><div className="rounded-xl bg-[#4A1F24] p-7 text-[#FAF8F3] md:p-9"><h2 className="text-2xl font-bold">Operating standards</h2><ul className="mt-6 space-y-5 leading-7 text-[#F5F1E8]"><li><strong className="text-white">Verified claims.</strong> We do not publish invented ratings, project counts, awards, or guarantees.</li><li><strong className="text-white">Defined scope.</strong> Work is separated into what Benson can perform, what requires a licensed specialty trade, and what needs engineering or regulated-material handling.</li><li><strong className="text-white">Rural planning.</strong> Route, access, materials, equipment, disposal, and weather are addressed before they become field problems.</li><li><strong className="text-white">Straight communication.</strong> Unknown conditions are identified as unknowns rather than hidden inside marketing language.</li></ul></div></section>

    <section className="border-y border-[#722F37]/10 bg-[#F5F1E8]"><div className="mx-auto max-w-6xl px-5 py-14 md:py-20"><p className="font-semibold uppercase tracking-[0.16em] text-[#722F37]">Harney County</p><h2 className="mt-2 text-3xl font-bold text-[#4A1F24] md:text-4xl">Local towns, ranches, and remote properties.</h2><p className="mt-4 max-w-3xl text-lg leading-8">Public service coverage is organized around Harney County. Individual project availability depends on scope, route fit, season, access, and current workload.</p><div className="mt-7 flex flex-wrap gap-3">{SERVICE_AREAS.harneyCounty.map(area => <span key={area} className="rounded-full border border-[#722F37]/20 bg-[#FAF8F3] px-4 py-2 font-semibold text-[#4A1F24]">{area}</span>)}</div><Link href="/service-area" className="mt-7 inline-block font-semibold text-[#722F37] underline underline-offset-4">Review service-area planning</Link></div></section>

    <section className="mx-auto max-w-5xl px-5 py-14 text-center md:py-20"><h2 className="text-3xl font-bold text-[#4A1F24]">Need a contractor to own the sequence, not just one task?</h2><p className="mx-auto mt-4 max-w-2xl leading-7">Send the property location and the full problem. We can determine which parts fit our scope and which dependencies need to be coordinated first.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/request-estimate" className="rounded-md bg-[#722F37] px-6 py-3 font-semibold text-white">Request an Estimate</Link><a href={`tel:${BUSINESS.phoneHref}`} className="rounded-md border border-[#722F37] px-6 py-3 font-semibold text-[#722F37]">Call {BUSINESS.phone}</a></div></section>
  </>;
}
